apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: kundenportal
      context: ../portal_github
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
