version: '2'
services:
  kundenportal-app:
    image: kundenportal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kundenportal-postgresql:5432/kundenportal
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://kundenportal-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://kundenportal-elasticsearch:9200
    ports:
      - 8080:8080
  kundenportal-postgresql:
    extends:
      file: postgresql.yml
      service: kundenportal-postgresql
  kundenportal-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: kundenportal-elasticsearch
