apiVersion: v1
kind: Service
metadata:
  name: kundenportal
  namespace: default
  labels:
    app: kundenportal
spec:
  selector:
    app: kundenportal
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
